# -*- coding: latin1 -*-

# Copyright 2011 Jeremy Nelson

# Copyright 2007 Casey Durfee
# Copyright 2008 Gabriel Sean Farrell
#
# This file is derived from the Kochief project.
# 
# Kochief is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Kochief is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Kochief.  If not, see <http://www.gnu.org/licenses/>.

AUDIENCE_CODING_MAP = {
    'a': 'Preschool', 
    'b': 'Primary', 
    'c': 'Pre-adolescent',
    'd': 'Adolescent', 
    'e': 'Adult', 
    'f': 'Specialized', 
    'g': 'General',
    'j': 'Juvenile', 
}

# got this from http://www.loc.gov/marc/languages/language_code.html
LANGUAGE_CODING_MAP = { 
    '   ': 'No information provided',
    'aar': 'Afar',
    'abk': 'Abkhaz',
    'ace': 'Achinese',
    'ach': 'Acoli',
    'ada': 'Adangme',
    'ady': 'Adygei',
    'afa': 'Afroasiatic (Other)',
    'afh': 'Afrihili (Artificial language)',
    'afr': 'Afrikaans',
    'ajm': 'Aljamía',
    'aka': 'Akan',
    'akk': 'Akkadian',
    'alb': 'Albanian',
    'ale': 'Aleut',
    'alg': 'Algonquian (Other)',
    'amh': 'Amharic',
    'ang': 'English, Old (ca. 450-1100)',
    'apa': 'Apache languages',
    'ara': 'Arabic',
    'arc': 'Aramaic',
    'arg': 'Aragonese Spanish',
    'arm': 'Armenian',
    'arn': 'Mapuche',
    'arp': 'Arapaho',
    'art': 'Artificial (Other)',
    'arw': 'Arawak',
    'asm': 'Assamese',
    'ast': 'Bable',
    'ath': 'Athapascan (Other)',
    'aus': 'Australian languages',
    'ava': 'Avaric',
    'ave': 'Avestan',
    'awa': 'Awadhi',
    'aym': 'Aymara',
    'aze': 'Azerbaijani',
    'bad': 'Banda',
    'bai': 'Bamileke languages',
    'bak': 'Bashkir',
    'bal': 'Baluchi',
    'bam': 'Bambara',
    'ban': 'Balinese',
    'baq': 'Basque',
    'bas': 'Basa',
    'bat': 'Baltic (Other)',
    'bej': 'Beja',
    'bel': 'Belarusian',
    'bem': 'Bemba',
    'ben': 'Bengali',
    'ber': 'Berber (Other)',
    'bho': 'Bhojpuri',
    'bih': 'Bihari',
    'bik': 'Bikol',
    'bin': 'Edo',
    'bis': 'Bislama',
    'bla': 'Siksika',
    'bnt': 'Bantu (Other)',
    'bos': 'Bosnian',
    'bra': 'Braj',
    'bre': 'Breton',
    'btk': 'Batak',
    'bua': 'Buriat',
    'bug': 'Bugis',
    'bul': 'Bulgarian',
    'bur': 'Burmese',
    'cad': 'Caddo',
    'cai': 'Central American Indian (Other)',
    'cam': 'Khmer',
    'car': 'Carib',
    'cat': 'Catalan',
    'cau': 'Caucasian (Other)',
    'ceb': 'Cebuano',
    'cel': 'Celtic (Other)',
    'cha': 'Chamorro',
    'chb': 'Chibcha',
    'che': 'Chechen',
    'chg': 'Chagatai',
    'chi': 'Chinese',
    'chk': 'Truk',
    'chm': 'Mari',
    'chn': 'Chinook jargon',
    'cho': 'Choctaw',
    'chp': 'Chipewyan',
    'chr': 'Cherokee',
    'chu': 'Church Slavic',
    'chv': 'Chuvash',
    'chy': 'Cheyenne',
    'cmc': 'Chamic languages',
    'cop': 'Coptic',
    'cor': 'Cornish',
    'cos': 'Corsican',
    'cpe': 'Creoles and Pidgins, English-based (Other)',
    'cpf': 'Creoles and Pidgins, French-based (Other)',
    'cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
    'cre': 'Cree',
    'crh': 'Crimean Tatar',
    'crp': 'Creoles and Pidgins (Other)',
    'cus': 'Cushitic (Other)',
    'cze': 'Czech',
    'dak': 'Dakota',
    'dan': 'Danish',
    'dar': 'Dargwa',
    'day': 'Dayak',
    'del': 'Delaware',
    'den': 'Slave',
    'dgr': 'Dogrib',
    'din': 'Dinka',
    'div': 'Divehi',
    'doi': 'Dogri',
    'dra': 'Dravidian (Other)',
    'dua': 'Duala',
    'dum': 'Dutch, Middle (ca. 1050-1350)',
    'dut': 'Dutch',
    'dyu': 'Dyula',
    'dzo': 'Dzongkha',
    'efi': 'Efik',
    'egy': 'Egyptian',
    'eka': 'Ekajuk',
    'elx': 'Elamite',
    'eng': 'English',
    'enm': 'English, Middle (1100-1500)',
    'epo': 'Esperanto',
    'esk': 'Eskimo languages',
    'esp': 'Esperanto',
    'est': 'Estonian',
    'eth': 'Ethiopic',
    'ewe': 'Ewe',
    'ewo': 'Ewondo',
    'fan': 'Fang',
    'fao': 'Faroese',
    'far': 'Faroese',
    'fat': 'Fanti',
    'fij': 'Fijian',
    'fin': 'Finnish',
    'fiu': 'Finno-Ugrian (Other)',
    'fon': 'Fon',
    'fre': 'French',
    'fri': 'Frisian',
    'frm': 'French, Middle (ca. 1400-1600)',
    'fro': 'French, Old (ca. 842-1400)',
    'fry': 'Frisian',
    'ful': 'Fula',
    'fur': 'Friulian',
    'gaa': 'Gã',
    'gae': 'Scottish Gaelic',
    'gag': 'Galician',
    'gal': 'Oromo',
    'gay': 'Gayo',
    'gba': 'Gbaya',
    'gem': 'Germanic (Other)',
    'geo': 'Georgian',
    'ger': 'German',
    'gez': 'Ethiopic',
    'gil': 'Gilbertese',
    'gla': 'Scottish Gaelic',
    'gle': 'Irish',
    'glg': 'Galician',
    'glv': 'Manx',
    'gmh': 'German, Middle High (ca. 1050-1500)',
    'goh': 'German, Old High (ca. 750-1050)',
    'gon': 'Gondi',
    'gor': 'Gorontalo',
    'got': 'Gothic',
    'grb': 'Grebo',
    'grc': 'Greek, Ancient (to 1453)',
    'gre': 'Greek, Modern (1453- )',
    'grn': 'Guarani',
    'gua': 'Guarani',
    'guj': 'Gujarati',
    'gwi': 'Gwich\'in',
    'hai': 'Haida',
    'hat': 'Haitian French Creole',
    'hau': 'Hausa',
    'haw': 'Hawaiian',
    'heb': 'Hebrew',
    'her': 'Herero',
    'hil': 'Hiligaynon',
    'him': 'Himachali',
    'hin': 'Hindi',
    'hit': 'Hittite',
    'hmn': 'Hmong',
    'hmo': 'Hiri Motu',
    'hun': 'Hungarian',
    'hup': 'Hupa',
    'iba': 'Iban',
    'ibo': 'Igbo',
    'ice': 'Icelandic',
    'ido': 'Ido',
    'iii': 'Sichuan Yi',
    'ijo': 'Ijo',
    'iku': 'Inuktitut',
    'ile': 'Interlingue',
    'ilo': 'Iloko',
    'ina': 'Interlingua (International Auxiliary Language Association)',
    'inc': 'Indic (Other)',
    'ind': 'Indonesian',
    'ine': 'Indo-European (Other)',
    'inh': 'Ingush',
    'ipk': 'Inupiaq',
    'ira': 'Iranian (Other)',
    'iri': 'Irish',
    'iro': 'Iroquoian (Other)',
    'ita': 'Italian',
    'jav': 'Javanese',
    'jpn': 'Japanese',
    'jpr': 'Judeo-Persian',
    'jrb': 'Judeo-Arabic',
    'kaa': 'Kara-Kalpak',
    'kab': 'Kabyle',
    'kac': 'Kachin',
    'kal': 'Kalâtdlisut',
    'kam': 'Kamba',
    'kan': 'Kannada',
    'kar': 'Karen',
    'kas': 'Kashmiri',
    'kau': 'Kanuri',
    'kaw': 'Kawi',
    'kaz': 'Kazakh',
    'kbd': 'Kabardian',
    'kha': 'Khasi',
    'khi': 'Khoisan (Other)',
    'khm': 'Khmer',
    'kho': 'Khotanese',
    'kik': 'Kikuyu',
    'kin': 'Kinyarwanda',
    'kir': 'Kyrgyz',
    'kmb': 'Kimbundu',
    'kok': 'Konkani',
    'kom': 'Komi',
    'kon': 'Kongo',
    'kor': 'Korean',
    'kos': 'Kusaie',
    'kpe': 'Kpelle',
    'kro': 'Kru',
    'kru': 'Kurukh',
    'kua': 'Kuanyama',
    'kum': 'Kumyk',
    'kur': 'Kurdish',
    'kus': 'Kusaie',
    'kut': 'Kutenai',
    'lad': 'Ladino',
    'lah': 'Lahnda',
    'lam': 'Lamba',
    'lan': 'Occitan (post-1500)',
    'lao': 'Lao',
    'lap': 'Sami',
    'lat': 'Latin',
    'lav': 'Latvian',
    'lez': 'Lezgian',
    'lim': 'Limburgish',
    'lin': 'Lingala',
    'lit': 'Lithuanian',
    'lol': 'Mongo-Nkundu',
    'loz': 'Lozi',
    'ltz': 'Letzeburgesch',
    'lua': 'Luba-Lulua',
    'lub': 'Luba-Katanga',
    'lug': 'Ganda',
    'lui': 'Luiseño',
    'lun': 'Lunda',
    'luo': 'Luo (Kenya and Tanzania)',
    'lus': 'Lushai',
    'mac': 'Macedonian',
    'mad': 'Madurese',
    'mag': 'Magahi',
    'mah': 'Marshallese',
    'mai': 'Maithili',
    'mak': 'Makasar',
    'mal': 'Malayalam',
    'man': 'Mandingo',
    'mao': 'Maori',
    'map': 'Austronesian (Other)',
    'mar': 'Marathi',
    'mas': 'Masai',
    'max': 'Manx',
    'may': 'Malay',
    'mdr': 'Mandar',
    'men': 'Mende',
    'mga': 'Irish, Middle (ca. 1100-1550)',
    'mic': 'Micmac',
    'min': 'Minangkabau',
    'mis': 'Miscellaneous languages',
    'mkh': 'Mon-Khmer (Other)',
    'mla': 'Malagasy',
    'mlg': 'Malagasy',
    'mlt': 'Maltese',
    'mnc': 'Manchu',
    'mni': 'Manipuri',
    'mno': 'Manobo languages',
    'moh': 'Mohawk',
    'mol': 'Moldavian',
    'mon': 'Mongolian',
    'mos': 'Mooré',
    'mul': 'Multiple languages',
    'mun': 'Munda (Other)',
    'mus': 'Creek',
    'mwr': 'Marwari',
    'myn': 'Mayan languages',
    'nah': 'Nahuatl',
    'nai': 'North American Indian (Other)',
    'nap': 'Neapolitan Italian',
    'nau': 'Nauru',
    'nav': 'Navajo',
    'nbl': 'Ndebele (South Africa)',
    'nde': 'Ndebele (Zimbabwe)  ',
    'ndo': 'Ndonga',
    'nds': 'Low German',
    'nep': 'Nepali',
    'new': 'Newari',
    'nia': 'Nias',
    'nic': 'Niger-Kordofanian (Other)',
    'niu': 'Niuean',
    'nno': 'Norwegian (Nynorsk)',
    'nob': 'Norwegian (Bokmål)',
    'nog': 'Nogai',
    'non': 'Old Norse',
    'nor': 'Norwegian',
    'nso': 'Northern Sotho',
    'nub': 'Nubian languages',
    'nya': 'Nyanja',
    'nym': 'Nyamwezi',
    'nyn': 'Nyankole',
    'nyo': 'Nyoro',
    'nzi': 'Nzima',
    'oci': 'Occitan (post-1500)',
    'oji': 'Ojibwa',
    'ori': 'Oriya',
    'orm': 'Oromo',
    'osa': 'Osage',
    'oss': 'Ossetic',
    'ota': 'Turkish, Ottoman',
    'oto': 'Otomian languages',
    'paa': 'Papuan (Other)',
    'pag': 'Pangasinan',
    'pal': 'Pahlavi',
    'pam': 'Pampanga',
    'pan': 'Panjabi',
    'pap': 'Papiamento',
    'pau': 'Palauan',
    'peo': 'Old Persian (ca. 600-400 B.C.)',
    'per': 'Persian',
    'phi': 'Philippine (Other)',
    'phn': 'Phoenician',
    'pli': 'Pali',
    'pol': 'Polish',
    'pon': 'Ponape',
    'por': 'Portuguese',
    'pra': 'Prakrit languages',
    'pro': 'Provençal (to 1500)',
    'pus': 'Pushto',
    'que': 'Quechua',
    'raj': 'Rajasthani',
    'rap': 'Rapanui',
    'rar': 'Rarotongan',
    'roa': 'Romance (Other)',
    'roh': 'Raeto-Romance',
    'rom': 'Romani',
    'rum': 'Romanian',
    'run': 'Rundi',
    'rus': 'Russian',
    'sad': 'Sandawe',
    'sag': 'Sango (Ubangi Creole)',
    'sah': 'Yakut',
    'sai': 'South American Indian (Other)',
    'sal': 'Salishan languages',
    'sam': 'Samaritan Aramaic',
    'san': 'Sanskrit',
    'sao': 'Samoan',
    'sas': 'Sasak',
    'sat': 'Santali',
    'scc': 'Serbian',
    'sco': 'Scots',
    'scr': 'Croatian',
    'sel': 'Selkup',
    'sem': 'Semitic (Other)',
    'sga': 'Irish, Old (to 1100)',
    'sgn': 'Sign languages',
    'shn': 'Shan',
    'sho': 'Shona',
    'sid': 'Sidamo',
    'sin': 'Sinhalese',
    'sio': 'Siouan (Other)',
    'sit': 'Sino-Tibetan (Other)',
    'sla': 'Slavic (Other)',
    'slo': 'Slovak',
    'slv': 'Slovenian',
    'sma': 'Southern Sami',
    'sme': 'Northern Sami',
    'smi': 'Sami',
    'smj': 'Lule Sami',
    'smn': 'Inari Sami',
    'smo': 'Samoan',
    'sms': 'Skolt Sami',
    'sna': 'Shona',
    'snd': 'Sindhi',
    'snh': 'Sinhalese',
    'snk': 'Soninke',
    'sog': 'Sogdian',
    'som': 'Somali',
    'son': 'Songhai',
    'sot': 'Sotho',
    'spa': 'Spanish',
    'srd': 'Sardinian',
    'srr': 'Serer',
    'ssa': 'Nilo-Saharan (Other)',
    'sso': 'Sotho',
    'ssw': 'Swazi',
    'suk': 'Sukuma',
    'sun': 'Sundanese',
    'sus': 'Susu',
    'sux': 'Sumerian',
    'swa': 'Swahili',
    'swe': 'Swedish',
    'swz': 'Swazi',
    'syr': 'Syriac',
    'tag': 'Tagalog',
    'tah': 'Tahitian',
    'tai': 'Tai (Other)',
    'taj': 'Tajik',
    'tam': 'Tamil',
    'tar': 'Tatar',
    'tat': 'Tatar',
    'tel': 'Telugu',
    'tem': 'Temne',
    'ter': 'Terena',
    'tet': 'Tetum',
    'tgk': 'Tajik',
    'tgl': 'Tagalog',
    'tha': 'Thai',
    'tib': 'Tibetan',
    'tig': 'Tigré',
    'tir': 'Tigrinya',
    'tiv': 'Tiv',
    'tkl': 'Tokelauan',
    'tli': 'Tlingit',
    'tmh': 'Tamashek',
    'tog': 'Tonga (Nyasa)',
    'ton': 'Tongan',
    'tpi': 'Tok Pisin',
    'tru': 'Truk',
    'tsi': 'Tsimshian',
    'tsn': 'Tswana',
    'tso': 'Tsonga',
    'tsw': 'Tswana',
    'tuk': 'Turkmen',
    'tum': 'Tumbuka',
    'tup': 'Tupi languages',
    'tur': 'Turkish',
    'tut': 'Altaic (Other)',
    'tvl': 'Tuvaluan',
    'twi': 'Twi',
    'tyv': 'Tuvinian',
    'udm': 'Udmurt',
    'uga': 'Ugaritic',
    'uig': 'Uighur',
    'ukr': 'Ukrainian',
    'umb': 'Umbundu',
    'und': 'Undetermined',
    'urd': 'Urdu',
    'uzb': 'Uzbek',
    'vai': 'Vai',
    'ven': 'Venda',
    'vie': 'Vietnamese',
    'vol': 'Volapük',
    'vot': 'Votic',
    'wak': 'Wakashan languages',
    'wal': 'Walamo',
    'war': 'Waray',
    'was': 'Washo',
    'wel': 'Welsh',
    'wen': 'Sorbian languages',
    'wln': 'Walloon',
    'wol': 'Wolof',
    'xal': 'Kalmyk',
    'xho': 'Xhosa',
    'yao': 'Yao (Africa)',
    'yap': 'Yapese',
    'yid': 'Yiddish',
    'yor': 'Yoruba',
    'ypk': 'Yupik languages',
    'zap': 'Zapotec',
    'zen': 'Zenaga',
    'zha': 'Zhuang',
    'znd': 'Zande',
    'zul': 'Zulu',
    'zun': 'Zuni',
    'zxx': 'No linguistic content'
}

DEWEY_MAP = {
    '000': 'Generalities',
    '001': 'Knowledge',
    '002': 'The book',
    '003': 'Systems',
    '004': 'Data processing Computer science',
    '005': 'Computer programming, programs, data',
    '006': 'Special computer methods',
    '007': 'Not assigned or no longer used',
    '008': 'Not assigned or no longer used',
    '009': 'Not assigned or no longer used',
    '010': 'Bibliography',
    '011': 'Bibliographies',
    '012': 'Bibliographies of individuals',
    '013': 'Bibliographies of works by specific classes of authors',
    '014': 'Bibliographies of anonymous and pseudonymous works',
    '015': 'Bibliographies of works from specific places',
    '016': 'Bibliographies of works from specific subjects',
    '017': 'General subject catalogs',
    '018': 'Catalogs arranged by author & date',
    '019': 'Dictionary catalogs',
    '020': 'Library & information sciences',
    '021': 'Library relationships',
    '022': 'Administration of the physical plant',
    '023': 'Personnel administration',
    '024': 'Not assigned or no longer used',
    '025': 'Library operations',
    '026': 'Libraries for specific subjects',
    '027': 'General libraries',
    '028': 'Reading, use of other information media',
    '029': 'Not assigned or no longer used',
    '030': 'General encyclopedic works',
    '031': 'General encyclopedic works -- American',
    '032': 'General encyclopedic works in English',
    '033': 'General encyclopedic works in other Germanic languages',
    '034': 'General encyclopedic works in French, Provencal, Catalan',
    '035': 'General encyclopedic works in Italian, Romanian, Rhaeto-Romanic',
    '036': 'General encyclopedic works in Spanish & Portuguese',
    '037': 'General encyclopedic works in Slavic languages',
    '038': 'General encyclopedic works in Scandinavian languages',
    '039': 'General encyclopedic works in other languages',
    '040': 'Not assigned or no longer used',
    '041': 'Not assigned or no longer used',
    '042': 'Not assigned or no longer used',
    '043': 'Not assigned or no longer used',
    '044': 'Not assigned or no longer used',
    '045': 'Not assigned or no longer used',
    '046': 'Not assigned or no longer used',
    '047': 'Not assigned or no longer used',
    '048': 'Not assigned or no longer used',
    '049': 'Not assigned or no longer used',
    '050': 'General serials & their indexes',
    '051': 'General serials & their indexes American',
    '052': 'General serials & their indexes In English',
    '053': 'General serials & their indexes In other Germanic languages',
    '054': 'General serials & their indexes In French, Provencal, Catalan',
    '055': 'General serials & their indexes In Italian, Romanian, Rhaeto-Romanic',
    '056': 'General serials & their indexes In Spanish & Portuguese',
    '057': 'General serials & their indexes In Slavic languages',
    '058': 'General serials & their indexes In Scandinavian languages',
    '059': 'General serials & their indexes In other languages',
    '060': 'General organization & museology',
    '061': 'General organization & museology In North America',
    '062': 'General organization & museology In British Isles In England',
    '063': 'General organization & museology In central Europe In Germany',
    '064': 'General organization & museology In France & Monaco',
    '065': 'General organization & museology In Italy & adjacent territories',
    '066': 'General organization & museology In Iberian Peninsula & adjacent islands',
    '067': 'General organization & museology In eastern Europe In Soviet Union',
    '068': 'General organization & museology In other areas',
    '069': 'Museology (Museum science)',
    '070': 'News media, journalism, publishing',
    '071': 'News media, journalism, publishing In North America',
    '072': 'News media, journalism, publishing In British Isles In England',
    '073': 'News media, journalism, publishing In central Europe In Germany',
    '074': 'News media, journalism, publishing In France & Monaco',
    '075': 'News media, journalism, publishing In Italy & adjacent territories',
    '076': 'News media, journalism, publishing In Iberian Peninsula & adjacent islands',
    '077': 'News media, journalism, publishing In eastern Europe In Soviet Union',
    '078': 'News media, journalism, publishing In Scandinavia',
    '079': 'News media, journalism, publishing In other languages',
    '080': 'General collections',
    '081': 'General collections American',
    '082': 'General collections In English',
    '083': 'General collections In other Germanic languages',
    '084': 'General collections In French, Provencal, Catalan',
    '085': 'General collections In Italian, Romanian, Rhaeto-Romanic',
    '086': 'General collections In Spanish & Portuguese',
    '087': 'General collections In Slavic languages',
    '088': 'General collections In Scandinavian languages',
    '089': 'General collections In other languages',
    '090': 'Manuscripts & rare books',
    '091': 'Manuscripts',
    '092': 'Block books',
    '093': 'Incunabula',
    '094': 'Printed books',
    '095': 'Books notable for bindings',
    '096': 'Books notable for illustrations',
    '097': 'Books notable for ownership or origin',
    '098': 'Prohibited works, forgeries, hoaxes',
    '099': 'Books notable for format',
    '100': 'Philosophy & psychology',
    '101': 'Theory of philosophy',
    '102': 'Miscellany of philosophy',
    '103': 'Dictionaries of philosophy',
    '104': 'Not assigned or no longer used',
    '105': 'Serial publications of philosophy',
    '106': 'Organizations of philosophy',
    '107': 'Education, research in philosophy',
    '108': 'Kinds of persons in philosophy',
    '109': 'Historical treatment of philosophy',
    '110': 'Metaphysics',
    '111': 'Ontology',
    '112': 'Not assigned or no longer used',
    '113': 'Cosmology (Philosophy of nature)',
    '114': 'Space',
    '115': 'Time',
    '116': 'Change',
    '117': 'Structure',
    '118': 'Force & Energy',
    '119': 'Number & quantity',
    '120': 'Epistemology, causation, humankind',
    '121': 'Epistemology (Theory of knowledge)',
    '122': 'Causation',
    '123': 'Determinism & indeterminism',
    '124': 'Teleology',
    '125': 'Not assigned or no longer used',
    '126': 'The self',
    '127': 'The unconscious & the subconscious',
    '128': 'Humankind',
    '129': 'Origin & destiny of individual souls',
    '130': 'Paranormal phenomena',
    '131': 'Occult methods for achieving well-being',
    '132': 'Not assigned or no longer used',
    '133': 'Parapsychology & occultism',
    '134': 'Not assigned or no longer used',
    '135': 'Dreams & mysteries',
    '136': 'Not assigned or no longer used',
    '137': 'Divinatory graphology',
    '138': 'Physiognomy',
    '139': 'Phrenology',
    '140': 'Specific philosophical schools',
    '141': 'Idealism & related systems',
    '142': 'Critical philosophy',
    '143': 'Intuitionism & Bergsonism',
    '144': 'Humanism & related systems',
    '145': 'Sensationalism',
    '146': 'Naturalism & related systems',
    '147': 'Pantheism & related systems',
    '148': 'Liberalism, eclecticism, traditionalism',
    '149': 'Other philosophical systems',
    '150': 'Psychology',
    '151': 'Not assigned or no longer used',
    '152': 'Perception, movement, emotions, drives',
    '153': 'Mental processes & intelligence',
    '154': 'Subconscious & altered states',
    '155': 'Differential & developmental psychology',
    '156': 'Comparative psychology',
    '157': 'Not assigned or no longer used',
    '158': 'Applied psychology',
    '159': 'Not assigned or no longer used',
    '160': 'Logic',
    '161': 'Induction',
    '162': 'Deduction',
    '163': 'Not assigned or no longer used',
    '164': 'Not assigned or no longer used',
    '165': 'Fallacies & sources of error',
    '166': 'Syllogisms',
    '167': 'Hypotheses',
    '168': 'Argument & persuasion',
    '169': 'Analogy',
    '170': 'Ethics (Moral philosophy)',
    '171': 'Systems & doctrines',
    '172': 'Political ethics',
    '173': 'Ethics of family relationships',
    '174': 'Economic & professional ethics',
    '175': 'Ethics of recreation & leisure',
    '176': 'Ethics of sex & reproduction',
    '177': 'Ethics of social relations',
    '178': 'Ethics of consumption',
    '179': 'Other ethical norms',
    '180': 'Ancient, medieval, Oriental philosophy',
    '181': 'Oriental philosophy',
    '182': 'Pre-Socratic Greek philosophies',
    '183': 'Sophistic & Socratic philosophies',
    '184': 'Platonic philosophy',
    '185': 'Aristotelian philosophy',
    '186': 'Skeptic and Neoplatonic philosophies',
    '187': 'Epicurean philosophy',
    '188': 'Stoic philosophy',
    '189': 'Medieval Western philosophy',
    '190': 'Modern Western philosophy',
    '191': 'Modern Western philosophy United States & Canada',
    '192': 'Modern Western philosophy British Isles',
    '193': 'Modern Western philosophy Germany & Austria',
    '194': 'Modern Western philosophy France',
    '195': 'Modern Western philosophy Italy',
    '196': 'Modern Western philosophy Spain & Portugal',
    '197': 'Modern Western philosophy Soviet Union',
    '198': 'Modern Western philosophy Scandinavia',
    '199': 'Modern Western philosophy Other geographical areas',
    '200': 'Religion',
    '201': 'Philosophy of Christianity',
    '202': 'Miscellany of Christianity',
    '203': 'Dictionaries of Christianity',
    '204': 'Special topics',
    '205': 'Serial publications of Christianity',
    '206': 'Organizations of Christianity',
    '207': 'Education, research in Christianity',
    '208': 'Kinds of persons in Christianity',
    '209': 'History & geography of Christianity',
    '210': 'Natural theology',
    '211': 'Concepts of God',
    '212': 'Existence, attributes of God',
    '213': 'Creation',
    '214': 'Theodicy',
    '215': 'Science & religion',
    '216': 'Good & evil',
    '217': 'Not assigned or no longer used',
    '218': 'Humankind',
    '219': 'Not assigned or no longer used',
    '220': 'Bible',
    '221': 'Old Testament',
    '222': 'Historical books of Old Testament',
    '223': 'Poetic books of Old Testament',
    '224': 'Prophetic books of Old Testament',
    '225': 'New Testament',
    '226': 'Gospels & Acts',
    '227': 'Epistles',
    '228': 'Revelation (Apocalypse)',
    '229': 'Apocrypha & pseudepigrapha',
    '230': 'Christian theology',
    '231': 'God',
    '232': 'Jesus Christ & his family',
    '233': 'Humankind',
    '234': 'Salvation (Soteriology) & grace',
    '235': 'Spiritual beings',
    '236': 'Eschatology',
    '237': 'Not assigned or no longer used',
    '238': 'Creeds & catechisms',
    '239': 'Apologetics & polemics',
    '240': 'Christian moral & devotional theology',
    '241': 'Moral theology',
    '242': 'Devotional literature',
    '243': 'Evangelistic writings for individuals',
    '244': 'Not assigned or no longer used',
    '245': 'Texts of hymns',
    '246': 'Use of art in Christianity',
    '247': 'Church furnishings & articles',
    '248': 'Christian experience, practice, life',
    '249': 'Christian observances in family life',
    '250': 'Christian orders & local church',
    '251': 'Preaching (Homiletics)',
    '252': 'Texts of sermons',
    '253': 'Pastoral office (Pastoral theology)',
    '254': 'Parish government & administration',
    '255': 'Religious congregations & orders',
    '256': 'Not assigned or no longer used',
    '257': 'Not assigned or no longer used',
    '258': 'Not assigned or no longer used',
    '259': 'Activities of the local church',
    '260': 'Christian social theology',
    '261': 'Social theology',
    '262': 'Ecclesiology',
    '263': 'Times, places of religious observance',
    '264': 'Public worship',
    '265': 'Sacraments, other rites & acts',
    '266': 'Missions',
    '267': 'Associations for religious work',
    '268': 'Religious education',
    '269': 'Spiritual renewal',
    '270': 'Christian church history',
    '271': 'Religious orders in church history',
    '272': 'Persecutions in church history',
    '273': 'Heresies in church history',
    '274': 'Christian church in Europe',
    '275': 'Christian church in Asia',
    '276': 'Christian church in Africa',
    '277': 'Christian church in North America',
    '278': 'Christian church in South America',
    '279': 'Christian church in other areas',
    '280': 'Christian denominations & sects',
    '281': 'Early church & Eastern churches',
    '282': 'Roman Catholic Church',
    '283': 'Anglican churches',
    '284': 'Protestants of Continental origin',
    '285': 'Presbyterian, Reformed, Congregational',
    '286': 'Baptist, Disciples of Christ, Adventist',
    '287': 'Methodist & related churches',
    '288': 'Not assigned or no longer used',
    '289': 'Other denominations & sects',
    '290': 'Other & comparative religions',
    '291': 'Comparative religion',
    '292': 'Classical (Greek & Roman) religion',
    '293': 'Germanic religion',
    '294': 'Religions of Indic origin',
    '295': 'Zoroastrianism (Mazdaism, Parseeism)',
    '296': 'Judaism',
    '297': 'Islam & religions originating in it',
    '298': 'Not assigned or no longer used',
    '299': 'Other religions',
    '300': 'Social sciences',
    '301': 'Sociology & anthropology',
    '302': 'Social interaction',
    '303': 'Social processes',
    '304': 'Factors affecting social behavior',
    '305': 'Social groups',
    '306': 'Culture & institutions',
    '307': 'Communities',
    '308': 'Not assigned or no longer used',
    '309': 'Not assigned or no longer used',
    '310': 'General statistics',
    '311': 'Not assigned or no longer used',
    '312': 'Not assigned or no longer used',
    '313': 'Not assigned or no longer used',
    '314': 'General statistics Of Europe',
    '315': 'General statistics Of Asia',
    '316': 'General statistics Of Africa',
    '317': 'General statistics Of North America',
    '318': 'General statistics Of South America',
    '319': 'General statistics Of other parts of the world',
    '320': 'Political science',
    '321': 'Systems of governments & states',
    '322': 'Relation of state to organized groups',
    '323': 'Civil & political rights',
    '324': 'The political process',
    '325': 'International migration & colonization',
    '326': 'Slavery & emancipation',
    '327': 'International relations',
    '328': 'The legislative process',
    '329': 'Not assigned or no longer used',
    '330': 'Economics',
    '331': 'Labor economics',
    '332': 'Financial economics',
    '333': 'Land economics',
    '334': 'Cooperatives',
    '335': 'Socialism & related systems',
    '336': 'Public finance',
    '337': 'International economics',
    '338': 'Production',
    '339': 'Macroeconomics & related topics',
    '340': 'Law',
    '341': 'International law',
    '342': 'Constitutional & administrative law',
    '343': 'Military, tax, trade, industrial law',
    '344': 'Social, labor, welfare, & related law',
    '345': 'Criminal law',
    '346': 'Private law',
    '347': 'Civil procedure & courts',
    '348': 'Law (Statutes), regulations, cases',
    '349': 'Law of specific jurisdictions & areas',
    '350': 'Public administration',
    '351': 'Of central governments',
    '352': 'Of local governments',
    '353': 'of U.S. federal & state governments',
    '354': 'Of specific central governments',
    '355': 'Military science',
    '356': 'Foot forces & warfare',
    '357': 'Mounted forces & warfare',
    '358': 'Other specialized forces & services',
    '359': 'Sea (Naval) forces & warfare',
    '360': 'Social services; association',
    '361': 'General social problems & services',
    '362': 'Social welfare problems & services',
    '363': 'Other social problems & services',
    '364': 'Criminology',
    '365': 'Penal & related institutions',
    '366': 'Association',
    '367': 'General clubs',
    '368': 'Insurance',
    '369': 'Miscellaneous kinds of associations',
    '370': 'Education',
    '371': 'School management; special education',
    '372': 'Elementary education',
    '373': 'Secondary education',
    '374': 'Adult education',
    '375': 'Curriculums',
    '376': 'Education of women',
    '377': 'Schools & religion',
    '378': 'Higher education',
    '379': 'Government regulation, control, support',
    '380': 'Commerce, communications, transport',
    '381': 'Internal commerce (Domestic trade)',
    '382': 'International commerce (Foreign trade)',
    '383': 'Postal communication',
    '384': 'Communications Telecommunication',
    '385': 'Railroad transportation',
    '386': 'Inland waterway & ferry transportation',
    '387': 'Water, air, space transportation',
    '388': 'Transportation Ground transportation',
    '389': 'Metrology & standardization',
    '390': 'Customs, etiquette, folklore',
    '391': 'Costume & personal appearance',
    '392': 'Customs of life cycle & domestic life',
    '393': 'Death customs',
    '394': 'General customs',
    '395': 'Etiquette (Manners)',
    '396': 'Not assigned or no longer used',
    '397': 'Not assigned or no longer used',
    '398': 'Folklore',
    '399': 'Customs of war & diplomacy',
    '400': 'Language',
    '401': 'Philosophy & theory',
    '402': 'Miscellany',
    '403': 'Dictionaries & encyclopedias',
    '404': 'Special topics',
    '405': 'Serial publications',
    '406': 'Organizations & management',
    '407': 'Education, research, related topics',
    '408': 'With respect to kinds of persons',
    '409': 'Geographical & persons treatment',
    '410': 'Linguistics',
    '411': 'Writing systems',
    '412': 'Etymology',
    '413': 'Dictionaries',
    '414': 'Phonology',
    '415': 'Structural systems (Grammar)',
    '416': 'Not assigned or no longer used',
    '417': 'Dialectology & historical linguistics',
    '418': 'Standard usage Applied linguistics',
    '419': 'Verbal language not spoken or written',
    '420': 'English & Old English',
    '421': 'English writing system & phonology',
    '422': 'English etymology',
    '423': 'English dictionaries',
    '424': 'Not assigned or no longer used',
    '425': 'English grammar',
    '426': 'Not assigned or no longer used',
    '427': 'English language variations',
    '428': 'Standard English usage',
    '429': 'Old English (Anglo-Saxon)',
    '430': 'Germanic languages German',
    '431': 'German writing system & phonology',
    '432': 'German etymology',
    '433': 'German dictionaries',
    '434': 'Not assigned or no longer used',
    '435': 'German grammar',
    '436': 'Not assigned or no longer used',
    '437': 'German language variations',
    '438': 'Standard German usage',
    '439': 'Other Germanic languages',
    '440': 'Romance languages French',
    '441': 'French writing system & phonology',
    '442': 'French etymology',
    '443': 'French dictionaries',
    '444': 'Not assigned or no longer used',
    '445': 'French grammar',
    '446': 'Not assigned or no longer used',
    '447': 'French language variations',
    '448': 'Standard French usage',
    '449': 'Provencal & Catalan',
    '450': 'Italian, Romanian, Rhaeto-Romantic',
    '451': 'Italian writing system & phonology',
    '452': 'Italian etymology',
    '453': 'Italian dictionaries',
    '454': 'Not assigned or no longer used',
    '455': 'Italian grammar',
    '456': 'Not assigned or no longer used',
    '457': 'Italian language variations',
    '458': 'Standard Italian usage',
    '459': 'Romanian & Rhaeto-Romanic',
    '460': 'Spanish & Portugese languages',
    '461': 'Spanish writing system & phonology',
    '462': 'Spanish etymology',
    '463': 'Spanish dictionaries',
    '464': 'Not assigned or no longer used',
    '465': 'Spanish grammar',
    '466': 'Not assigned or no longer used',
    '467': 'Spanish language variations',
    '468': 'Standard Spanish usage',
    '469': 'Portugese',
    '470': 'Italic Latin',
    '471': 'Classical Latin writing & phonology',
    '472': 'Classical Latin etymology & phonology',
    '473': 'Classical Latin dictionaries',
    '474': 'Not assigned or no longer used',
    '475': 'Classical Latin grammar',
    '476': 'Not assigned or no longer used',
    '477': 'Old, Postclassical, Vulgar Latin',
    '478': 'Classical Latin usage',
    '479': 'Other Italic languages',
    '480': 'Hellenic languages Classical Greek',
    '481': 'Classical Greek writing & phonology',
    '482': 'Classical Greek etymology',
    '483': 'Classical Greek dictionaries',
    '484': 'Not assigned or no longer used',
    '485': 'Classical Greek grammar',
    '486': 'Not assigned or no longer used',
    '487': 'Preclassical & postclassical Greek',
    '488': 'Classical Greek usage',
    '489': 'Other Hellenic languages',
    '490': 'Other languages',
    '491': 'East Indo-European & Celtic languages',
    '492': 'Afro-Asiatic languages Semitic',
    '493': 'Non-Semitic Afro-Asiatic languages',
    '494': 'Ural-Altaic, Paleosiberian, Dravidian',
    '495': 'Languages of East & Southeast Asia',
    '496': 'African languages',
    '497': 'North American native languages',
    '498': 'South American native languages',
    '499': 'Miscellaneous languages',
    '500': 'Natural sciences & mathematics',
    '501': 'Philosophy & theory',
    '502': 'Miscellany',
    '503': 'Dictionaries & encyclopedias',
    '504': 'Not assigned or no longer used',
    '505': 'Serial publications',
    '506': 'Organizations & management',
    '507': 'Education, research, related topics',
    '508': 'Natural history',
    '509': 'Historical, areas, persons treatment',
    '510': 'Mathematics',
    '511': 'General principles',
    '512': 'Algebra & number theory',
    '513': 'Arithmetic',
    '514': 'Topology',
    '515': 'Analysis',
    '516': 'Geometry',
    '517': 'Not assigned or no longer used',
    '518': 'Not assigned or no longer used',
    '519': 'Probabilities & applied mathematics',
    '520': 'Astronomy & allied sciences',
    '521': 'Celestial mechanics',
    '522': 'Techniques, equipment, materials',
    '523': 'Specific celestial bodies & phenomena',
    '524': 'Not assigned or no longer used',
    '525': 'Earth (Astronomical geography)',
    '526': 'Mathematical geography',
    '527': 'Celestial navigation',
    '528': 'Ephemerides',
    '529': 'Chronology',
    '530': 'Physics',
    '531': 'Classical mechanics Solid mechanics',
    '532': 'Fluid mechanics Liquid mechanics',
    '533': 'Gas mechanics',
    '534': 'Sound & related vibrations',
    '535': 'Light & paraphotic phenomena',
    '536': 'Heat',
    '537': 'Electricity & electronics',
    '538': 'Magnetism',
    '539': 'Modern physics',
    '540': 'Chemistry & allied sciences',
    '541': 'Physical & theoretical chemistry',
    '542': 'Techniques, equipment, materials',
    '543': 'Analytical chemistry',
    '544': 'Qualitative analysis',
    '545': 'Quantitative analysis',
    '546': 'Inorganic chemistry',
    '547': 'Organic chemistry',
    '548': 'Crystallography',
    '549': 'Mineralogy',
    '550': 'Earth sciences',
    '551': 'Geology, hydrology, meteorology',
    '552': 'Petrology',
    '553': 'Economic geology',
    '554': 'Earth sciences of Europe',
    '555': 'Earth sciences of Asia',
    '556': 'Earth sciences of Africa',
    '557': 'Earth sciences of North America',
    '558': 'Earth sciences of South America',
    '559': 'Earth sciences of other areas',
    '560': 'Paleontology Paleozoology',
    '561': 'Paleobotany',
    '562': 'Fossil invertebrates',
    '563': 'Fossil primitive phyla',
    '564': 'Fossil Mollusca & Molluscoidea',
    '565': 'Other fossil invertebrates',
    '566': 'Fossil Vertebrata (Fossil Craniata)',
    '567': 'Fossil cold-blooded vertebrates',
    '568': 'Fossil Aves (Fossil birds)',
    '569': 'Fossil Mammalia',
    '570': 'Life sciences',
    '571': 'Not assigned or no longer used',
    '572': 'Human races',
    '573': 'Physical anthropology',
    '574': 'Biology',
    '575': 'Evolution & genetics',
    '576': 'Microbiology',
    '577': 'General nature of life',
    '578': 'Microscopy in biology',
    '579': 'Collection and preservation',
    '580': 'Botanical sciences',
    '581': 'Botany',
    '582': 'Spermatophyta (Seed-bearing plants)',
    '583': 'Dicotyledones',
    '584': 'Monocotyledones',
    '585': 'Gymnospermae (Pinophyta)',
    '586': 'Cryptogamia (Seedless plants)',
    '587': 'Pteridophyta (Vascular cryptograms)',
    '588': 'Bryophyta',
    '589': 'Thallobionta & Prokaryotae',
    '590': 'Zoological sciences',
    '591': 'Zoology',
    '592': 'Invertebrates',
    '593': 'Protozoa, Echinodermata, related phyla',
    '594': 'Mollusca & Molluscoidea',
    '595': 'Other invertebrates',
    '596': 'Vertebrata (Craniata, Vertebrates)',
    '597': 'Cold-blooded vertebrates Fishes',
    '598': 'Aves (Birds)',
    '599': 'Mammalia (Mammals)',
    '600': 'Technology (Applied sciences)',
    '601': 'Philosophy & theory',
    '602': 'Miscellany',
    '603': 'Dictionaries & encyclopedias',
    '604': 'Special topics',
    '605': 'Serial publications',
    '606': 'Organizations',
    '607': 'Education, research, related topics',
    '608': 'Invention & patents',
    '609': 'Historical, areas, persons treatment',
    '610': 'Medical sciences Medicine',
    '611': 'Human anatomy, cytology, histology',
    '612': 'Human physiology',
    '613': 'Promotion of health',
    '614': 'Incidence & prevention of disease',
    '615': 'Pharmacology & theraputics',
    '616': 'Diseases',
    '617': 'Surgery & related medical specialities',
    '618': 'Gynecology & other medical specialities',
    '619': 'Experimental medicine',
    '620': 'Engineering & allied operations',
    '621': 'Applied physics',
    '622': 'Mining & related operations',
    '623': 'Military & nautical engineering',
    '624': 'Civil engineering',
    '625': 'Engineering of railroads, roads',
    '626': 'Not assigned or no longer used',
    '627': 'Hydraulic engineering',
    '628': 'Sanitary & municipal engineering',
    '629': 'Other branches of engineering',
    '630': 'Agriculture',
    '631': 'Techniques, equipment, materials',
    '632': 'Plant injuries, diseases, pests',
    '633': 'Field & plantation crops',
    '634': 'Orchards, fruits, forestry',
    '635': 'Garden crops (Horticulture)',
    '636': 'Animal husbandry',
    '637': 'Processing dairy & related products',
    '638': 'Insect culture',
    '639': 'Hunting, fishing, conservation',
    '640': 'Home economics & family living',
    '641': 'Food & drink',
    '642': 'Meals & table service',
    '643': 'Housing & household equipment',
    '644': 'Household utilities',
    '645': 'Household furnishings',
    '646': 'Sewing, clothing, personal living',
    '647': 'Management of public households',
    '648': 'Housekeeping',
    '649': 'Child rearing & home care of sick',
    '650': 'Management & auxiliary services',
    '651': 'Office services',
    '652': 'Processes of written communication',
    '653': 'Shorthand',
    '654': 'Not assigned or no longer used',
    '655': 'Not assigned or no longer used',
    '656': 'Not assigned or no longer used',
    '657': 'Accounting',
    '658': 'General management',
    '659': 'Advertising & public relations',
    '660': 'Chemical engineering',
    '661': 'Industrial chemicals technology',
    '662': 'Explosives, fuels technology',
    '663': 'Beverage technology',
    '664': 'Food technology',
    '665': 'Industrial oils, fats, waxes, gases',
    '666': 'Ceramic & allied technologies',
    '667': 'Cleaning, color, related technologies',
    '668': 'Technology of other organic products',
    '669': 'Metallurgy',
    '670': 'Manufacturing',
    '671': 'Metalworking & metal products',
    '672': 'Iron, steel, other iron alloys',
    '673': 'Nonferrous metals',
    '674': 'Lumber processing, wood products, cork',
    '675': 'Leather & fur processing',
    '676': 'Pulp & paper technology',
    '677': 'Textiles',
    '678': 'Elastomers & elastomer products',
    '679': 'Other products of specific materials',
    '680': 'Manufacture for specific uses',
    '681': 'Precision instruments & other devices',
    '682': 'Small forge work (Blacksmithing)',
    '683': 'Hardware & household appliances',
    '684': 'Furnishings & home workshops',
    '685': 'Leather, fur, related products',
    '686': 'Printing & related activities',
    '687': 'Clothing',
    '688': 'Other final products & packaging',
    '689': 'Not assigned or no longer used',
    '690': 'Buildings',
    '691': 'Building materials',
    '692': 'Auxiliary construction practices',
    '693': 'Specific materials & purposes',
    '694': 'Wood construction Carpentry',
    '695': 'Roof covering',
    '696': 'Utilities',
    '697': 'Heating, ventilating, air-conditioning',
    '698': 'Detail finishing',
    '699': 'Not assigned or no longer used',
    '700': 'The arts',
    '701': 'Philosophy & theory',
    '702': 'Miscellany',
    '703': 'Dictionaries & encyclopedias',
    '704': 'Special topics',
    '705': 'Serial publications',
    '706': 'Organizations & management',
    '707': 'Education, research, related topics',
    '708': 'Galleries, museums, private collections',
    '709': 'Historical, areas, persons treatment',
    '710': 'Civic & landscape art',
    '711': 'Area planning (Civic art)',
    '712': 'Landscape architecture',
    '713': 'Landscape architecture of trafficways',
    '714': 'Water features',
    '715': 'Woody plants',
    '716': 'Herbaceous plants',
    '717': 'Structures',
    '718': 'Landscape design of cemeteries',
    '719': 'Natural landscapes',
    '720': 'Architecture',
    '721': 'Architectural structure',
    '722': 'Architecture to ca. 300',
    '723': 'Architecture from ca. 300 to 1399',
    '724': 'Architecture from 1400',
    '725': 'Public structures',
    '726': 'Buildings for religious purposes',
    '727': 'Buildings for education & research',
    '728': 'Residential & related buildings',
    '729': 'Design & decoration',
    '730': 'Plastic arts Sculpture',
    '731': 'Processes, forms, subjects of sculpture',
    '732': 'Sculpture to ca. 500',
    '733': 'Greek, Etruscan, Roman sculpture',
    '734': 'Sculpture from ca. 500 to 1399',
    '735': 'Sculpture from 1400',
    '736': 'Carving & carvings',
    '737': 'Numismatics & sigillography',
    '738': 'Ceramic arts',
    '739': 'Art metalwork',
    '740': 'Drawing & decorative arts',
    '741': 'Drawing & drawings',
    '742': 'Perspective',
    '743': 'Drawing & drawings by subject',
    '744': 'Not assigned or no longer used',
    '745': 'Decorative arts',
    '746': 'Textile arts',
    '747': 'Interior decoration',
    '748': 'Glass',
    '749': 'Furniture & accessories',
    '750': 'Painting & paintings',
    '751': 'Techniques, equipment, forms',
    '752': 'Color',
    '753': 'Symbolism, allegory, mythology, legend',
    '754': 'Genre paintings',
    '755': 'Religion & religious symbolism',
    '756': 'Not assigned or no longer used',
    '757': 'Human figures & their parts',
    '758': 'Other subjects',
    '759': 'Historical, areas, persons treatment',
    '760': 'Graphic arts Printmaking & prints',
    '761': 'Relief processes (Block printing)',
    '762': 'Not assigned or no longer used',
    '763': 'Lithographic (Planographic) processes',
    '764': 'Chromolithography & serigraphy',
    '765': 'Metal engraving',
    '766': 'Mezzotinting & related processes',
    '767': 'Etching & drypoint',
    '768': 'Not assigned or no longer used',
    '769': 'Prints',
    '770': 'Photography & photographs',
    '771': 'Techniques, equipment, materials',
    '772': 'Metallic salt processes',
    '773': 'Pigment processes of printing',
    '774': 'Holography',
    '775': 'Not assigned or no longer used',
    '776': 'Not assigned or no longer used',
    '777': 'Not assigned or no longer used',
    '778': 'Fields & kinds of photography',
    '779': 'Photographs',
    '780': 'Music',
    '781': 'General principles & musical forms',
    '782': 'Vocal music',
    '783': 'Music for single voices The voice',
    '784': 'Instruments & Instrumental ensembles',
    '785': 'Chamber music',
    '786': 'Keyboard & other instruments',
    '787': 'Stringed instruments (Chordophones)',
    '788': 'Wind instruments (Aerophones)',
    '789': 'Not assigned or no longer used',
    '790': 'Recreational & performing arts',
    '791': 'Public performances',
    '792': 'Stage presentations',
    '793': 'Indoor games & amusements',
    '794': 'Indoor games of skill',
    '795': 'Games of chance',
    '796': 'Athletic & outdoor sports & games',
    '797': 'Aquatic & air sports',
    '798': 'Equestrian sports & animal racing',
    '799': 'Fishing, hunting, shooting',
    '800': 'Literature & rhetoric',
    '801': 'Philosophy & theory',
    '802': 'Miscellany',
    '803': 'Dictionaries & encyclopedias',
    '804': 'Not assigned or no longer used',
    '805': 'Serial publications',
    '806': 'Organizations',
    '807': 'Education, research, related topics',
    '808': 'Rhetoric & collections of literature',
    '809': 'Literary history & criticism',
    '810': 'American literature in English',
    '811': 'Poetry',
    '812': 'Drama',
    '813': 'Fiction',
    '814': 'Essays',
    '815': 'Speeches',
    '816': 'Letters',
    '817': 'Satire & humor',
    '818': 'Miscellaneous writings',
    '819': 'Not assigned or no longer used',
    '820': 'English & Old English literatures',
    '821': 'English poetry',
    '822': 'English drama',
    '823': 'English fiction',
    '824': 'English essays',
    '825': 'English speeches',
    '826': 'English letters',
    '827': 'English satire & humor',
    '828': 'English miscellaneous writings',
    '829': 'Old English (Anglo-Saxon)',
    '830': 'Literatures of Germanic languages',
    '831': 'German poetry',
    '832': 'German drama',
    '833': 'German fiction',
    '834': 'German essays',
    '835': 'German speeches',
    '836': 'German letters',
    '837': 'German satire & humor',
    '838': 'German miscellaneous writings',
    '839': 'Other Germanic literatures',
    '840': 'Literatures of Romance languages',
    '841': 'French poetry',
    '842': 'French drama',
    '843': 'French fiction',
    '844': 'French essays',
    '845': 'French speeches',
    '846': 'French letters',
    '847': 'French satire & humor',
    '848': 'French miscellaneous writings',
    '849': 'Provencal & Catalan',
    '850': 'Italian, Romanian, Rhaeto-Romanic',
    '851': 'Italian poetry',
    '852': 'Italian drama',
    '853': 'Italian fiction',
    '854': 'Italian essays',
    '855': 'Italian speeches',
    '856': 'Italian letters',
    '857': 'Italian satire & humor',
    '858': 'Italian miscellaneous writings',
    '859': 'Romanian & Rhaeto-Romanic',
    '860': 'Spanish & Portuguese literatures',
    '861': 'Spanish poetry',
    '862': 'Spanish drama',
    '863': 'Spanish fiction',
    '864': 'Spanish essays',
    '865': 'Spanish speeches',
    '866': 'Spanish letters',
    '867': 'Spanish satire & humor',
    '868': 'Spanish miscellaneous writings',
    '869': 'Portuguese',
    '870': 'Italic literatures Latin',
    '871': 'Latin poetry',
    '872': 'Latin dramatic poetry & drama',
    '873': 'Latin epic poetry & fiction',
    '874': 'Latin lyric poetry',
    '875': 'Latin speeches',
    '876': 'Latin letters',
    '877': 'Latin satire & humor',
    '878': 'Latin miscellaneous writings',
    '879': 'Literatures of other Italic languages',
    '880': 'Hellenic literatures Classical Greek',
    '881': 'Classical Greek poetry',
    '882': 'Classical Greek drama',
    '883': 'Classical Greek epic poetry & fiction',
    '884': 'Classical Greek lyric poetry',
    '885': 'Classical Greek speeches',
    '886': 'Classical Greek letters',
    '887': 'Classical Greek satire & humor',
    '888': 'Classical Greek miscellaneous writings',
    '889': 'Modern Greek',
    '890': 'Literatures of other languages',
    '891': 'East Indo-European & Celtic',
    '892': 'Afro-Asiatic literatures Semitic',
    '893': 'Non-Semitic Afro-Asiatic literatures',
    '894': 'Ural-Altaic, Paleosiberian, Dravidian',
    '895': 'Literatures of East & Southeast Asia',
    '896': 'African literatures',
    '897': 'North American native literatures',
    '898': 'South Anerican native literatures',
    '899': 'Other literatures',
    '900': 'Geography & history',
    '901': 'Philosophy & theory',
    '902': 'Miscellany',
    '903': 'Dictionaries & encyclopedias',
    '904': 'Collected accounts of events',
    '905': 'Serial publications',
    '906': 'Organizations & management',
    '907': 'Education, research, related topics',
    '908': 'With respect to kinds of persons',
    '909': 'World history',
    '910': 'Geography & travel',
    '911': 'Historical geography',
    '912': 'Graphic representations of earth',
    '913': 'Ancient world',
    '914': 'Europe',
    '915': 'Asia',
    '916': 'Africa',
    '917': 'North America',
    '918': 'South America',
    '919': 'Other areas',
    '920': 'Biography, genealogy, insignia',
    '921': 'Not assigned or no longer used',
    '922': 'Not assigned or no longer used',
    '923': 'Not assigned or no longer used',
    '924': 'Not assigned or no longer used',
    '925': 'Not assigned or no longer used',
    '926': 'Not assigned or no longer used',
    '927': 'Not assigned or no longer used',
    '928': 'Not assigned or no longer used',
    '929': 'Genealogy, names, insignia',
    '930': 'History of ancient world',
    '931': 'History of ancient world China',
    '932': 'History of ancient world Egypt',
    '933': 'History of ancient world Palestine',
    '934': 'History of ancient world India',
    '935': 'History of ancient world Mesopotamia & Iranian Plateau',
    '936': 'History of ancient world Europe north & west of Italy',
    '937': 'History of ancient world Italy & adjacent territories',
    '938': 'History of ancient world Greece',
    '939': 'History of ancient world Other parts of ancient world',
    '940': 'General history of Europe',
    '941': 'General history of Europe British Isles',
    '942': 'General history of Europe England & Wales',
    '943': 'General history of Europe Central Europe Germany',
    '944': 'General history of Europe France & Monaco',
    '945': 'General history of Europe Italian Peninsula & adjacent islands',
    '946': 'General history of Europe Iberian Peninsula & adjacent islands',
    '947': 'General history of Europe Eastern Europe Soviet Union',
    '948': 'General history of Europe Northern Europe Scandinavia',
    '949': 'General history of Europe Other parts of Europe',
    '950': 'General history of Asia Far East',
    '951': 'General history of Asia China & adjacent areas',
    '952': 'General history of Asia Japan',
    '953': 'General history of Asia Arabian Peninsula & adjacent areas',
    '954': 'General history of Asia South Asia India',
    '955': 'General history of Asia Iran',
    '956': 'General history of Asia Middle East (Near East)',
    '957': 'General history of Asia Siberia (Asiatic Russia)',
    '958': 'General history of Asia Central Asia',
    '959': 'General history of Asia Southeast Asia',
    '960': 'General history of Africa',
    '961': 'General history of Africa Tunisia & Libya',
    '962': 'General history of Africa Egypt & Sudan',
    '963': 'General history of Africa Ethiopia',
    '964': 'General history of Africa Morocco & Canary Islands',
    '965': 'General history of Africa Algeria',
    '966': 'General history of Africa West Africa & offshore islands',
    '967': 'General history of Africa Central Africa & offshore islands',
    '968': 'General history of Africa Southern Africa',
    '969': 'General history of Africa South Indian Ocean islands',
    '970': 'General history of North America',
    '971': 'General history of North America Canada',
    '972': 'General history of North America Middle America Mexico',
    '973': 'General history of North America United States',
    '974': 'General history of North America Northeastern United States',
    '975': 'General history of North America Southeastern United States',
    '976': 'General history of North America South central United States',
    '977': 'General history of North America North central United States',
    '978': 'General history of North America Western United States',
    '979': 'General history of North America Great Basin & Pacific Slope',
    '980': 'General history of South America',
    '981': 'General history of South America Brazil',
    '982': 'General history of South America Argentina',
    '983': 'General history of South America Chile',
    '984': 'General history of South America Bolivia',
    '985': 'General history of South America Peru',
    '986': 'General history of South America Colombia & Ecuador',
    '987': 'General history of South America Venezuela',
    '988': 'General history of South America Guiana',
    '989': 'General history of South America Paraguay & Uruguay',
    '990': 'General history of other areas',
    '991': 'Not assigned or no longer used',
    '992': 'Not assigned or no longer used',
    '993': 'General history of other areas New Zealand',
    '994': 'General history of other areas Australia',
    '995': 'General history of other areas Melanesia New Guinea',
    '996': 'General history of other areas Other parts of Pacific Polynesia',
    '997': 'General history of other areas Atlantic Ocean islands',
    '998': 'General history of other areas Arctic islands & Antarctica',
    '999': 'Extraterrestrial worlds',
}

ROLE_CODING_MAP = {
    'act': 'Actor',
    'adp': 'Adapter',
    'aft': 'Author of afterword, colophon, etc.',
    'ann': 'Annotator',
    'ant': 'Bibliographic antecedent',
    'app': 'Applicant',
    'aqt': 'Author in quotations or text abstracts',
    'arc': 'Architect',
    'arr': 'Arranger',
    'art': 'Artist',
    'asg': 'Assignee',
    'asn': 'Associated name',
    'att': 'Attributed name',
    'auc': 'Auctioneer',
    'aud': 'Author of dialog',
    'aui': 'Author of introduction',
    'aus': 'Author of screenplay',
    'aut': 'Author',
    'bdd': 'Binding designer',
    'bjd': 'Bookjacket designer',
    'bkd': 'Book designer',
    'bkp': 'Book producer',
    'bnd': 'Binder',
    'bpd': 'Bookplate designer',
    'bsl': 'Bookseller',
    'ccp': 'Conceptor',
    'chr': 'Choreographer',
    'clb': 'Collaborator',
    'cli': 'Client',
    'cll': 'Calligrapher',
    'clt': 'Collotyper',
    'cmm': 'Commentator',
    'cmp': 'Composer',
    'cmt': 'Compositor',
    'cnd': 'Conductor',
    'cns': 'Censor',
    'coe': 'Contestant-appellee',
    'col': 'Collector',
    'com': 'Compiler',
    'cos': 'Contestant',
    'cot': 'Contestant-appellant',
    'cpc': 'Copyright claimant',
    'cpe': 'Complainant-appellee',
    'cph': 'Copyright holder',
    'cpl': 'Complainant',
    'cpt': 'Complainant-appellant',
    'cre': 'Creator',
    'crp': 'Correspondent',
    'crr': 'Corrector',
    'csl': 'Consultant',
    'csp': 'Consultant to a project',
    'cst': 'Costume designer',
    'ctb': 'Contributor',
    'cte': 'Contestee-appellee',
    'ctg': 'Cartographer',
    'ctr': 'Contractor',
    'cts': 'Contestee',
    'ctt': 'Contestee-appellant',
    'cur': 'Curator',
    'cwt': 'Commentator for written text',
    'dfd': 'Defendant',
    'dfe': 'Defendant-appellee',
    'dft': 'Defendant-appellant',
    'dgg': 'Degree grantor',
    'dis': 'Dissertant',
    'dln': 'Delineator',
    'dnc': 'Dancer',
    'dnr': 'Donor',
    'dpt': 'Depositor',
    'drm': 'Draftsman',
    'drt': 'Director',
    'dsr': 'Designer',
    'dst': 'Distributor',
    'dte': 'Dedicatee',
    'dto': 'Dedicator',
    'dub': 'Dubious author',
    'edt': 'Editor',
    'egr': 'Engraver',
    'elt': 'Electrotyper',
    'eng': 'Engineer',
    'etr': 'Etcher',
    'exp': 'Expert',
    'fac': 'Facsimilist',
    'flm': 'Film editor',
    'fmo': 'Former owner',
    'fnd': 'Funder',
    'frg': 'Forger',
    'grt': 'Graphic technician',
    'hnr': 'Honoree',
    'hst': 'Host',
    'ill': 'Illustrator',
    'ilu': 'Illuminator',
    'ins': 'Inscriber',
    'inv': 'Inventor',
    'itr': 'Instrumentalist',
    'ive': 'Interviewee',
    'ivr': 'Interviewer',
    'lbt': 'Librettist',
    'lee': 'Libelee-appellee',
    'lel': 'Libelee',
    'len': 'Lender',
    'let': 'Libelee-appellant',
    'lie': 'Libelant-appellee',
    'lil': 'Libelant',
    'lit': 'Libelant-appellant',
    'lsa': 'Landscape architect',
    'lse': 'Licensee',
    'lso': 'Licensor',
    'ltg': 'Lithographer',
    'lyr': 'Lyricist',
    'mdc': 'Metadata contact',
    'mod': 'Moderator',
    'mon': 'Monitor',
    'mte': 'Metal-engraver',
    'mus': 'Musician',
    'nrt': 'Narrator',
    'opn': 'Opponent',
    'org': 'Originator',
    'orm': 'Organizer of meeting',
    'oth': 'Other',
    'own': 'Owner',
    'pat': 'Patron',
    'pbd': 'Publishing director',
    'pbl': 'Publisher',
    'pfr': 'Proofreader',
    'pht': 'Photographer',
    'plt': 'Platemaker',
    'pop': 'Printer of plates',
    'ppm': 'Papermaker',
    'prc': 'Process contact',
    'prd': 'Production personnel',
    'prf': 'Performer',
    'prg': 'Programmer',
    'pro': 'Producer',
    'prt': 'Printer',
    'pta': 'Patent applicant',
    'pte': 'Plaintiff-appellee',
    'ptf': 'Plaintiff',
    'pth': 'Patent holder',
    'ptt': 'Plaintiff-appellant',
    'rbr': 'Rubricator',
    'rce': 'Recording engineer',
    'rcp': 'Recipient',
    'red': 'Redactor',
    'ren': 'Renderer',
    'res': 'Researcher',
    'rev': 'Reviewer',
    'rse': 'Respondent-appellee',
    'rsp': 'Respondent',
    'rst': 'Respondent-appellant',
    'rth': 'Research team head',
    'rtm': 'Research team member',
    'sad': 'Scientific advisor',
    'sce': 'Scenarist',
    'scr': 'Scribe',
    'scl': 'Sculptor',
    'sec': 'Secretary',
    'sgn': 'Signer',
    'sng': 'Singer',
    'spk': 'Speaker',
    'spn': 'Sponsor',
    'srv': 'Surveyor',
    'stn': 'Standards body',
    'str': 'Stereotyper',
    'ths': 'Thesis advisor',
    'trc': 'Transcriber',
    'trl': 'Translator',
    'tyd': 'Type designer',
    'tyg': 'Typographer',
    'voc': 'Vocalist',
    'wam': 'Writer of accompanying material',
    'wdc': 'Woodcutter',
    'wde': 'Wood-engraver',
    'wit': 'Witness ',
}

LC_CALLNUMBER_MAP = {
    "AC":"AC - Collections Works",
    "AE":"AE - Encyclopedias",
    "AG":"AG - General Reference Works",
    "AI":"AI - Indexes",
    "AM":"AM - Museums",
    "AN":"AN - Newspapers",
    "AP":"AP - Periodicals",
    "AS":"AS - Academies & Learned Societies",
    "AY":"AY - Yearbooks, Almanacs, Directories",
    "AZ":"AZ - History of Scholarship & Learning",
    "A":"A - General Works",
    "BC":"BC - Logic",
    "BD":"BD - Speculative Philosophy",
    "BF":"BF - Psychology",
    "BH":"BH - Aesthetics",
    "BJ":"BJ - Ethics",
    "BL":"BL - Religions (General)",
    "BM":"BM - Judaism",
    "BP":"BP - Islam, Bahaism, Theosophy, etc.",
    "BQ":"BQ - Buddhism",
    "BR":"BR - Christianity",
    "BS":"BS - The Bible",
    "BT":"BT - Doctrinal Theology",
    "BV":"BV - Practical Theology",
    "BX":"BX - Christian Denominations",
    "B":"B - Philosophy, Psychology, Religion",
    "CB":"CB - History of Civilization",
    "CC":"CC - Archaeology",
    "CD":"CD - Diplomatics",
    "CE":"CE - Technical Chronology",
    "CJ":"CJ - Numismatics",
    "CN":"CN - Inscriptions",
    "CR":"CR - Heraldry",
    "CS":"CS - Genealogy",
    "CT":"CT - Biography",
    "C":"C - Historical Sciences (Archaeology, Genealogy)",
    "DA":"DA - Great Britain (History)",
    "DB":"DB - Austria, Liechtenstein, Czech Rep., Hungary, Slovakia (History)",
    "DC":"DC - France (History)",
    "DD":"DD - Germany (History)",
    "DE":"DE - Greco-Roman World (History)",
    "DF":"DF - Greece (History)",
    "DG":"DG - Italy (History)",
    "DH":"DH - Low Countries (History)",
    "DJK":"DJK - Eastern Europe (History)",
    "DJ":"DJ - Netherlands (History)",
    "DK":"DK - Russia. Former Soviet Republics. Poland (History)",
    "DL":"DL - Scandinavia (History)",
    "DP":"DP - Spain. Portugal (History)",
    "DQ":"DQ - Switzerland (History)",
    "DR":"DR - Balkan Peninsula (History)",
    "DS":"DS - Asia (History)",
    "DT":"DT - Africa (History)",
    "DU":"DU - Oceania (History)",
    "DX":"DX - Gypsies (History)",
    "D":"D - World History",
    "E":"E - History of the Americas (General)",
    "F":"F - History of the Americas (Local)",
    "GA":"GA - Mathematical Geography, Cartography",
    "GB":"GB - Physical Geography",
    "GC":"GC - Oceanography",
    "GE":"GE - Environmental Sciences",
    "GF":"GF - Human Ecology, Anthropogeography",
    "GN":"GN - Anthropology",
    "GR":"GR - Folklore",
    "GT":"GT - Manners & Customs",
    "GV":"GV - Recreation. Leisure",
    "G":"G - Geography, Anthropology, Recreation",
    "HA":"HA - Statistics",
    "HB":"HB - Economic Theory, Demography",
    "HC":"HC - Economic History & Conditions",
    "HD":"HD - Industries, Land use, Labor",
    "HE":"HE - Transportation & Communications",
    "HF":"HF - Commerce",
    "HG":"HG - Finance",
    "HJ":"HJ - Public Finance",
    "HM":"HM - Sociology",
    "HN":"HN - Social History & Conditions",
    "HQ":"HQ - The Family, Marriage, Woman",
    "HS":"HS - Societies",
    "HT":"HT - Communities, Classes, Races",
    "HV":"HV - Social Pathology, Social & Public Welfare, Criminology",
    "HX":"HX - Socialism, Communism, Anarchism",
    "H":"H - Social Sciences",
    "JA":"JA - Political Science",
    "JC":"JC - Political Theory",
    "JF":"JF - Political Institutions",
    "JK":"JK - Political Institutions (U.S.)",
    "JL":"JL - Political Institutions (Canada, Latin America)",
    "JN":"JN - Political Institutions (Europe)",
    "JQ":"JQ - Political Institutions (Asia, Africa, Australia, Pacific Area)",
    "JS":"JS - Local Government",
    "JV":"JV - Colonies & Colonization, Emigration & Immigration",
    "JX":"JX - International Law",
    "JZ":"JZ - International Relations",
    "J":"J - Political Science",
    "KBM":"KBM - Jewish Law",
    "KBP":"KBP - Islamic Law",
    "KBR":"KBR - Canon Law",
    "KBU":"KBU - Law of Roman Catholic Church",
    "KB":"KB - Religious Law (General)",
    "KDC":"KDC - Law of Scotland",
    "KDE":"KDE - Law of Northern Ireland",
    "KDG":"KDG - Law of Isle of Man, Channel Islands",
    "KDK":"KDK - Law of Ireland (EIRE)",
    "KDZ":"KDZ - Law of America, North America",
    "KD":"KD - Law of England & Wales",
    "KE":"KE - Law of Canada",
    "KF":"KF - Law of the U.S.",
    "KG":"KG - Law of Latin America, Mexico, Central America, West Indies, Caribbean",
    "KH":"KH - South America",
    "KJA":"KJA - Roman Law",
    "KJC":"KJC - Regional Comparative & Uniform Law",
    "KJE":"KJE - Regional Organization & Integration",
    "KJG":"KJG - Law of Albania",
    "KJH":"KJH - Law of Andorra",
    "KJJ":"KJJ - Law of Austria",
    "KJK":"KJK - Law of Belgium, Bosnia & Hercegovina (Republic)",
    "KJM":"KJM - Law of Bulgaria, Croatia",
    "KJN":"KJN - Law of Cyprus",
    "KJP":"KJP - Law of Czechoslovakia, Czech Republic",
    "KJQ":"KJQ - Law of Slovakia",
    "KJR":"KJR - Law of Denmark",
    "KJS":"KJS - Law of Estonia",
    "KJT":"KJT - Law of Finland",
    "KJV":"KJV - Law of France",
    "KJW":"KJW - Law of French Regions, Provinces, Departments",
    "KJ":"KJ - Law of Europe",
    "KKE":"KKE - Law of Greece",
    "KKF":"KKF - Law of Hungary",
    "KKG":"KKG - Law of Iceland",
    "KKH":"KKH - Law of Italy",
    "KKI":"KKI - Law of Latvia",
    "KKJ":"KKJ - Law of Lithuania, Liechtenstein",
    "KKK":"KKK - Law of Luxemburg, Malta",
    "KKL":"KKL - Law of Monaco",
    "KKM":"KKM - Law of the Netherlands",
    "KKN":"KKN - Law of Norway",
    "KKP":"KKP - Law of Poland",
    "KKQ":"KKQ - Law of Portugal",
    "KKR":"KKR - Law of Romania",
    "KKT":"KKT - Law of Spain",
    "KKV":"KKV - Law of Sweden",
    "KKW":"KKW - Law of Switzerland",
    "KKX":"KKX - Law of Turkey",
    "KKY":"KKY - Law of Ukraine",
    "KKZ":"KKZ - Law of Yugoslavia",
    "KK":"KK - Law of Germany",
    "KLA":"KLA - Law of Russia, Soviet Union",
    "KLB":"KLB - Law of Russia (Federation)",
    "KLD":"KLD - Law of Armenia (Republic)",
    "KLE":"KLE - Law of Azerbaijan",
    "KLF":"KLF - Law of Belarus",
    "KLH":"KLH - Law of Georgia",
    "KLM":"KLM - Law of Moldova",
    "KLP":"KLP - Law of Ukraine",
    "KLR":"KLR - Law of Kazakhstan",
    "KLS":"KLS - Law of Kyrgyzstan",
    "KLT":"KLT - Law of Tajikistan",
    "KLV":"KLV - Law of Turkmenistan",
    "KLW":"KLW - Law of Uzbekistan",
    "KL":"KL - History of Law, The Ancient Orient",
    "KMC":"KMC - Law of the Middle East, Southwest Asia",
    "KMH":"KMH - Law of Iran",
    "KMJ":"KMJ - Law of Iraq",
    "KMK":"KMK - Law of Israel",
    "KML":"KML - Law of Jerusalem",
    "KMM":"KMM - Law of Jordan",
    "KMN":"KMN - Law of Kuwait",
    "KMP":"KMP - Law of Lebanon",
    "KMT":"KMT - Law of Saudi Arabia",
    "KMU":"KMU - Law of Syria",
    "KMX":"KMX - Law of Yemen",
    "KM":"KM - Law of Asia",
    "KNC":"KNC - Law of South Asia",
    "KNN":"KNN - Law of China",
    "KNP":"KNP - Law of Taiwan",
    "KNR":"KNR - Law of Hong Kong",
    "KNS":"KNS - Law of India",
    "KNW":"KNW - Law of Indonesia",
    "KNX":"KNX - Law of Japan",
    "KPA":"KPA - Law of Korea, South Korea",
    "KPC":"KPC - Law of Korea, North Korea",
    "KQ":"KQ - Law of Africa",
    "KU":"KU - Law of the Pacific Area, Australia, New Zealand",
    "KWX":"KWX - Law of Antarctica",
    "KZ":"KZ - Law of Nations",
    "K":"K - Law",
    "LA":"LA - History of Education",
    "LB":"LB - Theory & Practice of Education",
    "LC":"LC - Special Aspects of Education",
    "LD":"LD - Individual Educational Institutions (U.S.)",
    "LE":"LE - Individual Educational Institutions: America (except U.S.)",
    "LF":"LF - Individual Educational Institutions: Europe",
    "LG":"LG - Individual Educational Institutions: Asia, Africa, Oceania",
    "LH":"LH - College & School Magazines & Papers",
    "LT":"LT - Textbooks",
    "L":"L - Education",
    "MLCME":"Unknown",
    "MLCSN":"Unknown",
    "ML":"ML - Literature on Music",
    "MT":"MT - Musical Instruction & Study",
    "M":"M - Music",
    "NA":"NA - Architecture",
    "NB":"NB - Sculpture",
    "NC":"NC - Drawing, Design, Illustration",
    "ND":"ND - Painting",
    "NE":"NE - Print Media",
    "NK":"NK - Decorative Arts",
    "NX":"NX - Arts in General",
    "N":"N - Fine Arts",
    "PA":"PA - Greek & Latin Language & Literature",
    "PB":"PB - Modern Language, Celtic Languages",
    "PC":"PC - Romanic Languages",
    "PD":"PD - Germanic Languages",
    "PE":"PE - English Languages",
    "PF":"PF - West Germanic Languages",
    "PG":"PG - Slavic, Baltic, Albanian Languages, Russian Language & Literature",
    "PH":"PH - Uralic & Basque Languages",
    "PJ":"PJ - Oriental Languages & Literature",
    "PK":"PK - Indo-Iranian Languages & Literature",
    "PL":"PL - Languages & Literatures of Eastern Asia, Africa, Oceania",
    "PM":"PM - Hyperborean, Indian & Artificial Languages",
    "PN":"PN - Literature (General)",
    "PQ":"PQ - French, Italian, Spanish & Portuguese Literature",
    "PR":"PR - English Literature",
    "PS":"PS - American Literature",
    "PT":"PT - Germanic & Scandinavian Literatures",
    "PZ":"PZ - Children's Literature",
    "P":"P - Language & Literature",
    "QA":"QA - Mathematics",
    "QB":"QB - Astronomy",
    "QC":"QC - Physics",
    "QD":"QD - Chemistry",
    "QE":"QE - Geology",
    "QH":"QH - Natural History, Biology",
    "QK":"QK - Botany",
    "QL":"QL - Zoology",
    "QM":"QM - Human Anatomy",
    "QP":"QP - Physiology",
    "QR":"QR - Microbiology",
    "Q":"Q - Science",
    "RA":"RA - Public Aspects of Medicine",
    "RB":"RB - Pathology",
    "RC":"RC - Internal Medicine",
    "RD":"RD - Surgery",
    "RE":"RE - Ophthalmology",
    "RF":"RF - Otorhinolaryngology",
    "RG":"RG - Gynecology & Obstetrics",
    "RJ":"RJ - Pediatrics",
    "RK":"RK - Dentistry",
    "RL":"RL - Dermatology",
    "RM":"RM - Therapeutics, Pharmacology",
    "RS":"RS - Pharmacy & Materia Medica",
    "RT":"RT - Nursing",
    "RV":"RV - Botanic, Thomsonian, & Eclectic Medicine",
    "RX":"RX - Homeopathy",
    "RZ":"RZ - Other Systems of Medicine",
    "R":"R - Medicine",
    "SB":"SB - Plant Culture",
    "SD":"SD - Forestry",
    "SF":"SF - Animal Culture",
    "SH":"SH - Aquaculture",
    "SK":"SK - Hunting Sports",
    "S":"S - Agriculture",
    "TA":"TA - Engineering, Civil Engineering",
    "TC":"TC - Hydraulic Engineering",
    "TD":"TD - Environmental Technology",
    "TE":"TE - Highway Engineering",
    "TF":"TF - Railroad Engineering & Operation",
    "TG":"TG - Bridge Engineering",
    "TH":"TH - Building Construction",
    "TJ":"TJ - Mechanical Engineering & Machinery",
    "TK":"TK - Electrical Engineering, Nuclear Engineering",
    "TL":"TL - Motor Vehicles, Aeronautics, Astronautics",
    "TN":"TN - Mining Engineering",
    "TP":"TP - Chemical Technology",
    "TR":"TR - Photography",
    "TS":"TS - Manufactures",
    "TT":"TT - Handicrafts",
    "TX":"TX - Home Economics",
    "T":"T - Technology",
    "UA":"UA - Armies",
    "UB":"UB - Military Administration",
    "UC":"UC - Maintenance & Transportation",
    "UD":"UD - Infantry",
    "UE":"UE - Cavalry, Armor",
    "UF":"UF - Artillery",
    "UG":"UG - Military Engineering, Air Forces, Military Astronautics",
    "UH":"UH - Other Military Services",
    "U":"U - Military Science",
    "VA":"VA - Navies",
    "VB":"VB - Naval Administration",
    "VC":"VC - Naval Maintenance",
    "VD":"VD - Naval Seamen",
    "VE":"VE - Marines",
    "VF":"VF - Naval Ordnance",
    "VG":"VG - Minor Services of Navies",
    "VK":"VK - Navigation, Merchant Marine",
    "VM":"VM - Naval Architecture, Marine Engineering",
    "V":"V - Naval Science",
    "ZA":"ZA - Information Science",
    "Z":"Z - Bibliography, Library Science, Information Resources",
}

DEWEY_CALLNUMBER_MAP = {
    "000":"000s - Computer Science, Information & General Works",
    "010":"010s - Bibliography",
    "020":"020s - Library & Information Sciences",
    "030":"030s - General Encyclopedic Works",
    "050":"050s - General Serials & their Indexes",
    "060":"060s - General Organization & Museology",
    "070":"070s - News Media, Journalism, Publishing",
    "080":"080s - General Collections",
    "090":"090s - Manuscripts & Rare Books",
    "100":"100s - Philosophy & Psychology",
    "110":"110s - Metaphysics",
    "120":"120s - Epistemology, Causation, Humankind",
    "130":"130s - Paranormal Phenomena",
    "140":"140s - Specific Philosophical Schools",
    "150":"150s - Psychology",
    "160":"160s - Logic",
    "170":"170s - Ethics (Moral Philosophy)",
    "180":"180s - Ancient, Medieval, Oriental Philosophy",
    "190":"190s - Modern Western Philosophy",
    "200":"200s - Religion",
    "210":"210s - Natural Theology",
    "220":"220s - Bible",
    "230":"230s - Christian Theology",
    "240":"240s - Christian Moral & Devotional Theology",
    "250":"250s - Christian Orders & Local Church",
    "260":"260s - Christian Social Theology",
    "270":"270s - Christian Church History",
    "280":"280s - Christian Denominations & Sects",
    "290":"290s - Other & Comparative Religions",
    "300":"300s - Social Sciences",
    "310":"310s - General Statistics",
    "320":"320s - Political Science",
    "330":"330s - Economics",
    "340":"340s - Law",
    "350":"350s - Public Administration",
    "360":"360s - Social Services; Association",
    "370":"370s - Education",
    "380":"380s - Commerce, Communications, Transport",
    "390":"390s - Customs, Etiquette, Folklore",
    "400":"400s - Language",
    "410":"410s - Linguistics",
    "420":"420s - English & Old English",
    "430":"430s - Germanic Languages German",
    "440":"440s - Romance Languages French",
    "450":"450s - Italian, Romanian, Rhaeto-Romantic",
    "460":"460s - Spanish & Portugese Languages",
    "470":"470s - Italic Latin",
    "480":"480s - Hellenic Languages Classical Greek",
    "490":"490s - Other Languages",
    "500":"500s - Science",
    "510":"510s - Mathematics",
    "520":"520s - Astronomy & Allied Sciences",
    "530":"530s - Physics",
    "540":"540s - Chemistry & Allied Sciences",
    "550":"550s - Earth Sciences",
    "560":"560s - Paleontology Paleozoology",
    "570":"570s - Life Sciences",
    "580":"580s - Botanical Sciences",
    "590":"590s - Zoological Sciences",
    "600":"600s - Technology",
    "610":"610s - Medical Sciences Medicine",
    "620":"620s - Engineering & Allied Operations",
    "630":"630s - Agriculture",
    "640":"640s - Home economics & Family Living",
    "650":"650s - Management & Auxiliary Services",
    "660":"660s - Chemical Engineering",
    "670":"670s - Manufacturing",
    "680":"680s - Manufacture for Specific Uses",
    "690":"690s - Buildings",
    "700":"700s - Arts & Recreation",
    "710":"710s - Civic & Landscape Art",
    "720":"720s - Architecture",
    "730":"730s - Plastic Arts Sculpture",
    "740":"740s - Drawing & Decorative Arts",
    "750":"750s - Painting & Paintings",
    "760":"760s - Graphic Arts Printmaking & Prints",
    "770":"770s - Photography & Photographs",
    "780":"780s - Music",
    "790":"790s - Recreational & Performing Arts",
    "800":"800s - Literature",
    "810":"810s - American Literature in English",
    "820":"820s - English & Old English Literatures",
    "830":"830s - Literatures of Germanic Languages",
    "840":"840s - Literatures of Romance Languages",
    "850":"850s - Italian, Romanian, Rhaeto-Romanic",
    "860":"860s - Spanish & Portuguese Literatures",
    "870":"870s - Italic Literatures Latin",
    "880":"880s - Hellenic Literatures Classical Greek",
    "890":"890s - Literatures of Other Languages",
    "900":"900s - History & Geography",
    "910":"910s - Geography & Travel",
    "920":"920s - Biography, Genealogy, Insignia",
    "930":"930s - History of Ancient World",
    "940":"940s - General History of Europe",
    "950":"950s - General History of Asia Far East",
    "960":"960s - General History of Africa",
    "970":"970s - General History of North America",
    "980":"980s - General History of South America",
    "990":"990s - General History of Other Areas",
}
