#
# Tutt library III location codes
# 
LOCATION_CODE_MAP = {
    'ewww':'Online',
    'ewwwd':'Online',
    'ewwwp':'Online',
    'ewwwn':'Online',
    'tarf':'Tutt Reference',
    'tarfa':'Tutt 1st Floor South',
    'tarfc':'Tutt Reference',
    'tarfd':'Tutt Reference Desk',
    'tarfg':'Tutt Reference Desk',
    'tarfi':'Tutt Reference',
    'tarfm':'Tutt Reference North 2nd Floor',
    'tarfo':'Tutt Reference North 2nd Floor',
    'tban':'Art Reading Room Tutt 2nd Floor South',
    'tbanf':'Art Reading Room Tutt 2nd Floor South',
    'tb':'Tutt 3rd Floor',
    'tbnc':'Tutt 3rd Floor',
    'tbndp':'Tutt Display',
    'tbnew':'Tutt New Arrivals',
    'tbp':'Tutt North Basement',
    'tbpnc':'Tutt North Basement',
    'tcat':'Tutt Cataloging Office',
    'tcas':'CDROM/Cassette Tutt Circulation Desk',
    'tcbs':'Tutt Leisure Reading',
    'tcurr':'Tutt 3rd Floor',
    'tdacd':'Government Documents CD-ROM index',
    'tfly':'On The Fly',
    'tgr':'Tutt North Basement',
    'tor':'Technical Services',
    'tr':'On Order',
    'tre':'Electronic Reserves',
    'trp':'Reserves Tutt 1st Floor',
    'trrm':'Reserves Tutt 1st Floor',
    'trs':'Reserves Tutt 1st Floor',
    'trsdo':'Reserves Tutt 1st Floor',
    'trstv':'Reserves Tutt 1st Floor',
    'td':'Tutt South Basement',
    'tdo':'Tutt South Basement',
    'tdcol':'Tutt South Basement',
    'tde':'Tutt South Basement',
    'tdea':'Tutt South Basement',
    'tdem':'Tutt South Basement',
    'tdemc':'Tutt South Basement',
    'tdn':'Tutt South Basement',
    'tdi':'Tutt 1st Floor South',
    'tdm':'Tutt 1st Floor South',
    'tdmt':'Tutt 1st Floor South',
    'tdmf':'Tutt 1st Floor South',
    'tdmi':'Microforms Tutt 2nd Floor',
    'tdof':'Tutt 1st Floor South',
    'tdscs':'Tutt 1st Floor South',
    'tmaps':'Tutt North 2nd Floor Map File',
    'tmi':'Microforms Tutt 2nd Floor',
    'tmic':'Microforms Tutt 2nd Floor',
    'tmico':'Microforms Tutt 2nd Floor',
    'tmics':'Microforms Tutt 2nd Floor',
    'tmifs':'Microforms Tutt 2nd Floor',
    'tt':'Tutt North Basement Theses',
    'ttlc':'Teaching Learning Center',
    'ttla':'Tutt North Basement Lit Award',
    'xfb':'Fine Arts Center',
    'xm':'Music Library',
    'xmcas':'Music Library',
    'xmcat':'Music Library',
    'xmcd':'Music Library',
    'xmdvd':'Music Library',
    'xmedd':'Music Library',
    'xmfly':'Music Library',
    'xmh':'Music Library',
    'xmhs':'Music Library',
    'xmhsm':'Music Library',
    'xmins':'Music Library',
    'xmld':'Music Library',
    'xmlp1':'Music Library',
    'xmmcd':'Music Library',
    'xmmi':'Music Library',
    'xmo':'Music Library',
    'xmor':'Music Library',
    'xmper':'Music Library',
    'xms':'Music Library',
    'xmr':'Music Library',
    'xmrt':'Music Library',
    'xmrs':'Music Library',
    'xmscm':'Music Library',
    'xmv':'Music Library',
    'tper':'Periodicals Tutt 2nd Floor',
    'tpero':'Periodicals Tutt 2nd Floor',
    'tdmo':'Oversize Tutt 2nd Floor',
    'tf':'Folio Tutt 3rd Floor',
    'to':'Oversize Tutt 3rd Floor',
    'xmscm':'Musical Scores',
    'tsa':'Special Collections Audio',
    'tlr':'Special Collections Lincoln Room',
    'tlrc':'Special Collections Lincoln Room',
    'tlrf':'Special Collections Lincoln Room',
    'tlro':'Special Collections Lincoln Room',
    'tlrp':'Special Collections Lincoln Room',
    'tlrpa':'Special Collections Lincoln Room',
    'tscc':'Special Collections CC Room',
    'tsccf':'Special Collections CC Room',
    'tscco':'Special Collections CC Room',
    'tsccp':'Special Collections CC Room',
    'tsnv':'Special Collections CC Room',
    'tsco':'Special Collections Colorado Room',
    'tscof':'Special Collections Colorado Room',
    'tscoo':'Special Collections Colorado Room',
    'tscop':'Special Collections Colorado Room',
    'tsm':'Special Collections Maps',
    'tsmi':'Special Collections Microform',
    'tsmf':'Special Collections Manuscripts',
    'tsms':'Special Collections Manuscripts',
    'tsof':'Special Collections Offices',
    'tsra':'Special Collections Rare',
    'tsraf':'Special Collections Rare',
    'tsrao':'Special Collections Rare',
    'tsrat':'Special Collections Rare',
    'tsse':'Special Collections Special Editions',
    'tssef':'Special Collections Special Editions',
    'tsseo':'Special Collections Special Editions',
    'tsset':'Special Collections Special Editions',
    'tssto':'Special Collections Storage Basement',
    'tsv':'Special Collections Videos',
    'tv':'Videos-Tutt 2nd Floor North',
    'tvc':'Video-Tutt Circulation Desk',
    'tvdvd':'DVD-Tutt Circulation Desk',
    'xbaca':'Baca Campus',
    'xfb':'Fine Arts Center',
    'xfcab':'Fine Arts Center',
    'xfdsk':'Fine Arts Center',
    'xfdvd':'Fine Arts Center',
    'xffil':'Fine Arts Center',
    'xfup':'Fine Arts Center',
    'xfo':'Fine Arts Center',
    'xfv':'Fine Arts Center',
    'xsan':'Anthropology Seminar-Barnes',
    'xsby':'Biology Seminar-Olin',
    'xsbyo':'Biology Seminar-Olin',
    'xsch':'Barnes Chemistry Library',
    'xscho':'Barnes Chemistry Library',
    'xsed':'Education Dept. (Mierow)',
    'xsedc':'Education Dept. (Mierow)',
    'xsedl':'Education Dept. Computer Lab',
    'xsedp':'Education Dept. (Mierow)',
    'xserc':'Environmental Science Seminar',
    'xsetv':'Environmental Science Seminar',
    'xsgeo':'Geology Map Room',
    'xsgix':'Keck GIS Commons',
    'xsgm':'Geology Map Room',
    'xsmat':'Math Seminar-Palmer',
    'xsph':'Physics Seminar-Barnes',
    'xspho':'Physics Seminar-Barnes',
    'xsps':'Political Science Seminar-Palmer',
    'xsrus':'Russian Seminar-Armstrong',
    'xwebb':'Penrose Hospital',
}
